services:
  reolinkproxy:
    image: ghcr.io/shareed2k/reolinkproxy:latest
    container_name: wildcam-reolinkproxy
    network_mode: host
    restart: unless-stopped
    env_file:
      - ./reolinkproxy.env
    environment:
      - REOLINK_HEALTHCHECK_RTSP_ONLY=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
