#!/usr/bin/env python3
"""
Neolink Manager für WildCam
Generiert automatisch neolink.toml aus camera_config.json für Battery-Kameras (Port 9000)
"""
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse, unquote

def parse_rtsp_url(rtsp_url):
    """Parse RTSP URL und extrahiere Komponenten.

    Hinweis: '#' in Passwörtern muss normalerweise URL-encoded (%23) sein.
    Wir erlauben hier bewusst allow_fragments=False, damit unescaped '#'
    nicht als Fragment abgeschnitten wird.
    """
    try:
        u = urlparse(rtsp_url, allow_fragments=False)
        if not u.hostname and "#" in rtsp_url:
            sanitized = rtsp_url.replace("#", "%23")
            u = urlparse(sanitized, allow_fragments=False)
        if u.hostname:
            return {
                'host': u.hostname,
                'port': u.port or 554,
                'username': u.username or '',
                'password': u.password or '',
                'scheme': u.scheme
            }
    except Exception:
        pass

    # Fallback: manuelles Parsing, falls urlparse versagt (z.B. unescaped '#')
    try:
        pattern = r'^[a-z]+://(?:([^:@/]+)(?::([^@/]*))?@)?([^:/]+)(?::(\d+))?'
        match = re.match(pattern, rtsp_url, re.IGNORECASE)
        if not match:
            return None
        username = unquote(match.group(1) or '')
        password = unquote(match.group(2) or '')
        host = match.group(3)
        port = int(match.group(4) or 554)
        return {
            'host': host,
            'port': port,
            'username': username,
            'password': password,
            'scheme': 'rtsp'
        }
    except Exception:
        return None

def is_baichuan_camera(camera):
    """Prüfe ob Kamera Baichuan-Protokoll (Port 9000) nutzt."""
    url_info = parse_rtsp_url(camera.get('url', ''))
    if not url_info:
        return False
    return url_info['port'] == 9000

def generate_neolink_config(camera_config_path, output_path='neolink.toml'):
    """Generiere neolink.toml aus camera_config.json."""
    
    # Lade camera_config.json
    try:
        with open(camera_config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except FileNotFoundError:
        print(f"❌ Fehler: {camera_config_path} nicht gefunden!")
        return False
    except json.JSONDecodeError as e:
        print(f"❌ Fehler beim Parsen der Config: {e}")
        return False
    
    cameras = config.get('cameras', [])
    
    # Filtere Battery-Kameras (Port 9000)
    battery_cameras = [cam for cam in cameras if is_baichuan_camera(cam)]
    
    if not battery_cameras:
        print("ℹ️  Keine Battery-Kameras (Port 9000) gefunden.")
        print("   Neolink wird nicht benötigt.")
        return False
    
    print(f"🔋 {len(battery_cameras)} Battery-Kamera(s) gefunden:")
    for cam in battery_cameras:
        print(f"   - {cam['name']} ({cam['url']})")
    
    # Generiere neolink.toml
    toml_content = """# Auto-generated by WildCam neolink_manager.py
# This file is automatically created from camera_config.json

bind = "0.0.0.0"
bind_port = 8554

"""
    
    for cam in battery_cameras:
        url_info = parse_rtsp_url(cam['url'])
        if not url_info:
            continue
        
        cam_name = cam['name'].replace(' ', '_')
        uid = cam.get('uid', '')
        
        toml_content += f"""
[[cameras]]
name = "{cam_name}"
username = "{url_info['username']}"
password = "{url_info['password']}"
address = "{url_info['host']}:9000"
"""
        
        if uid:
            toml_content += f'uid = "{uid}"\n'
        
        toml_content += """
# Battery optimization
idle_disconnect = true

[cameras.pause]
on_client = true
timeout = 2.1

"""
    
    # Schreibe neolink.toml
    try:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(toml_content)
        print(f"✅ {output_path} erfolgreich erstellt!")
        return True
    except Exception as e:
        print(f"❌ Fehler beim Schreiben: {e}")
        return False

def update_camera_config(camera_config_path):
    """Aktualisiere camera_config.json: Ersetze Port 9000 URLs mit localhost:8554."""
    
    try:
        with open(camera_config_path, 'r', encoding='utf-8') as f:
            config = json.load(f)
    except Exception as e:
        print(f"❌ Fehler beim Laden der Config: {e}")
        return False
    
    cameras = config.get('cameras', [])
    updated = False
    
    for cam in cameras:
        url_info = parse_rtsp_url(cam['url'])
        if url_info and url_info['port'] == 9000:
            # Ersetze mit Neolink localhost URL
            cam_name = cam['name'].replace(' ', '_')
            new_url = f"rtsp://localhost:8554/{cam_name}/mainStream"
            
            print(f"🔄 {cam['name']}: {cam['url']}")
            print(f"   → {new_url}")
            
            cam['url'] = new_url
            updated = True
    
    if updated:
        # Backup erstellen
        backup_path = f"{camera_config_path}.backup"
        try:
            with open(camera_config_path, 'r') as f:
                with open(backup_path, 'w') as backup:
                    backup.write(f.read())
            print(f"💾 Backup erstellt: {backup_path}")
        except Exception:
            pass
        
        # Aktualisierte Config speichern
        try:
            with open(camera_config_path, 'w', encoding='utf-8') as f:
                json.dump(config, f, indent=2, ensure_ascii=False)
            print(f"✅ {camera_config_path} aktualisiert!")
            return True
        except Exception as e:
            print(f"❌ Fehler beim Speichern: {e}")
            return False
    else:
        print("ℹ️  Keine Updates nötig.")
        return False

def main():
    script_dir = Path(__file__).parent
    config_path = script_dir / 'camera_config.json'
    
    print("🚀 WildCam Neolink Manager")
    print("=" * 50)
    
    # 1. Generiere neolink.toml
    print("\n📝 Schritt 1: Generiere neolink.toml...")
    success = generate_neolink_config(config_path)
    
    if not success:
        sys.exit(0)
    
    # 2. Frage ob Config aktualisiert werden soll
    print("\n" + "=" * 50)
    print("📋 Schritt 2: Camera Config aktualisieren?")
    print("   Ersetzt Port 9000 URLs mit localhost:8554 (Neolink)")
    
    if '--auto-update' in sys.argv or '--yes' in sys.argv:
        update = True
    else:
        response = input("   Fortfahren? [j/N]: ").lower()
        update = response in ['j', 'ja', 'y', 'yes']
    
    if update:
        update_camera_config(config_path)
    else:
        print("ℹ️  Übersprungen. URLs bleiben unverändert.")
    
    print("\n" + "=" * 50)
    print("✨ Fertig!")
    print("\nNächste Schritte:")
    print("  1. docker-compose up -d    # Startet Neolink")
    print("  2. python main.py           # Startet WildCam")

if __name__ == '__main__':
    main()
