#!/usr/bin/env python3
"""
ReolinkProxy Manager fuer WildCam.

Generiert reolinkproxy.env ausschliesslich aus camera_config.json.
"""
import json
import sys
from pathlib import Path

from camera_utils import (
    _parse_rtsp_url,
    _reolinkproxy_camera_name,
    _reolinkproxy_proxy_config,
    _reolinkproxy_rtsp_url,
)


def parse_rtsp_url(rtsp_url):
    host, port, username, password = _parse_rtsp_url(rtsp_url or "")
    if not host:
        return None
    return {
        "host": host,
        "port": port,
        "username": username or "",
        "password": password or "",
        "scheme": "rtsp",
    }


def camera_name(name):
    return _reolinkproxy_camera_name(name)


def is_proxy_url(rtsp_url):
    info = parse_rtsp_url(rtsp_url or "")
    return bool(info and info["host"] in ("localhost", "127.0.0.1") and info["port"] == 8554)


def is_reolinkproxy_camera(camera):
    proxy = camera.get("proxy") or {}
    if proxy.get("type") == "reolinkproxy":
        return True

    url_info = parse_rtsp_url(camera.get("url", ""))
    if url_info and url_info["port"] == 9000:
        return True
    return False


def env_value(value):
    value = "" if value is None else str(value)
    value = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{value}"'


def make_proxy_from_rtsp(camera):
    return _reolinkproxy_proxy_config(
        rtsp_url=camera.get("url", ""),
        name=camera.get("name", ""),
        username="",
        password="",
        uid=camera.get("uid", ""),
        model=camera.get("model", ""),
        manufacturer=camera.get("manufacturer", ""),
    )


def write_env(cameras, output_path):
    lines = [
        "# Auto-generated by WildCam reolinkproxy_manager.py",
        "# Existing WildCam RTSP paths are preserved with REOLINK_CAMERA_N_RTSP_PATH.",
        "REOLINK_HEALTHCHECK_RTSP_ONLY=true",
        "",
    ]

    proxy_cameras = [cam for cam in cameras if is_reolinkproxy_camera(cam)]
    incomplete_proxy_cameras = [
        cam for cam in cameras
        if is_proxy_url(cam.get("url", "")) and (cam.get("proxy") or {}).get("type") != "reolinkproxy"
    ]
    if incomplete_proxy_cameras:
        names = ", ".join(camera_name(cam.get("name", "")) for cam in incomplete_proxy_cameras)
        print(f"Unvollstaendige Proxy-Konfiguration fuer: {names}")
        print("Bitte in camera_config.json je Kamera einen proxy-Block mit host/username/password ergaenzen.")
        return False
    if not proxy_cameras:
        print("Keine ReolinkProxy-Kameras gefunden.")
        return False

    print(f"{len(proxy_cameras)} ReolinkProxy-Kamera(s) gefunden:")

    for index, cam in enumerate(proxy_cameras):
        name = camera_name(cam.get("name", f"Camera_{index}"))
        proxy = cam.get("proxy") or make_proxy_from_rtsp(cam) or {}

        use_uid_only = bool(proxy.get("uid_only", False))
        host = "" if use_uid_only else proxy.get("host", "")
        port = int(proxy.get("port") or 9000)
        username = proxy.get("username", "")
        password = proxy.get("password", "")
        stream = proxy.get("stream", "main")
        uid = proxy.get("uid") or cam.get("uid", "")
        battery = bool(proxy.get("battery", True))
        pause_on_client = bool(proxy.get("pause_on_client", True))
        idle_disconnect = bool(proxy.get("idle_disconnect", True))
        idle_timeout = proxy.get("idle_timeout", "30s")

        print(f"  - {name}: host={host or 'UID-only'}, uid={uid or '-'}")

        lines.extend(
            [
                f"REOLINK_CAMERA_{index}_NAME={env_value(name)}",
                f"REOLINK_CAMERA_{index}_PORT={port}",
                f"REOLINK_CAMERA_{index}_USERNAME={env_value(username)}",
                f"REOLINK_CAMERA_{index}_PASSWORD={env_value(password)}",
                f"REOLINK_CAMERA_{index}_STREAM={env_value(stream)}",
                f"REOLINK_CAMERA_{index}_RTSP_PATH={env_value(f'{name}/mainStream')}",
                f"REOLINK_CAMERA_{index}_BATTERY_CAMERA={str(battery).lower()}",
                f"REOLINK_CAMERA_{index}_PAUSE_ON_CLIENT={str(pause_on_client).lower()}",
                f"REOLINK_CAMERA_{index}_IDLE_DISCONNECT={str(idle_disconnect).lower()}",
                f"REOLINK_CAMERA_{index}_IDLE_TIMEOUT={env_value(idle_timeout)}",
            ]
        )
        if host:
            lines.append(f"REOLINK_CAMERA_{index}_HOST={env_value(host)}")
        if uid:
            lines.append(f"REOLINK_CAMERA_{index}_UID={env_value(uid)}")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"{output_path} geschrieben.")
    return True


def update_camera_config(camera_config_path):
    try:
        config = json.loads(camera_config_path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"Fehler beim Laden der Config: {e}")
        return False

    updated = False
    for cam in config.get("cameras", []):
        if not is_reolinkproxy_camera(cam):
            continue
        name = camera_name(cam.get("name", ""))
        if "proxy" not in cam:
            proxy = make_proxy_from_rtsp(cam)
            if proxy:
                cam["proxy"] = proxy
                updated = True
        new_url = _reolinkproxy_rtsp_url(name)
        if cam.get("url") != new_url:
            print(f"{cam.get('name', name)}: {cam.get('url')} -> {new_url}")
            cam["url"] = new_url
            updated = True

    if not updated:
        return False

    backup_path = camera_config_path.with_suffix(camera_config_path.suffix + ".backup")
    backup_path.write_text(camera_config_path.read_text(encoding="utf-8"), encoding="utf-8")
    camera_config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{camera_config_path} aktualisiert, Backup: {backup_path}")
    return True


def main():
    script_dir = Path(__file__).parent
    config_path = script_dir / "camera_config.json"
    env_path = script_dir / "reolinkproxy.env"

    print("WildCam ReolinkProxy Manager")
    print("=" * 50)

    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        print(f"Fehler: {config_path} nicht gefunden.")
        sys.exit(0)
    except json.JSONDecodeError as e:
        print(f"Fehler beim Parsen der Config: {e}")
        sys.exit(1)

    success = write_env(config.get("cameras", []), env_path)
    if not success:
        sys.exit(0)

    if "--auto-update" in sys.argv or "--yes" in sys.argv:
        update_camera_config(config_path)
    else:
        print("camera_config.json bleibt unveraendert. Nutze --auto-update zum Umschreiben alter Port-9000-URLs.")


if __name__ == "__main__":
    main()
